services:
  - type: web
    name: securityinsta
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    region: oregon
    runtime: python
    branch: main
    repo: https://github.com/Dwip272004/securityinsta

